name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 20

      # ... rest of the workflow ...

      - name: Upload Build Output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: path/to/build/output
