[app]
title = Disease Alert
package.name = Disease_Alert
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait

[buildozer]
log_level = 2
warn_on_root = 1

[android]
arch = arm64-v8a, armeabi-v7a
allow_backup = True

[ios]
kivy_ios_url = https://github.com/kivy/kivy-ios
kivy_ios_branch = master
ios_deploy_url = https://github.com/phonegap/ios-deploy
ios_deploy_branch = master
