name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 20

      - name: Build Android App
        run: |
          # ... build commands ...

          # Save build output as artifact
          echo "Build output saved as build-output.tar.gz"
          mv path/to/build/output build-output.tar.gz

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: build-output.tar.gz

      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: path/to/download/output

      - name: Make package available for download
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: path/to/download/output
