name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 20

      # - name: Set up JDK
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      # - name: Build with Gradle
      #   run: ./gradlew build

      # - name: Package Android App
      #   run: ./gradlew assembleRelease

      - name: Upload Build Output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: path/to/build/output

