name: Disease Alert

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/main-debug.apk

      - name: Upload Python artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-artifacts
          path: main.py

      - name: Upload requirements artifact
        uses: actions/upload-artifact@v2
        with:
          name: requirements
          path: requirements.txt
             
