name: Build and Package Python Web Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Package artifacts
        uses: actions/upload-artifact@v2
        with: "C:\Users\Ann Margaret Ruelan\Documents\python\onion bulb diseases detector app"
          name:python-web-app
          path:|
            app/views.py
            app/__init__.py
            app/templates/
            app/static/
            requirements.txt
            README.md # Optional, if you want to include the README
