name: Disease Alert

on:
  push:
    branches: main 

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # ... rest of the workflow ...

      - name: Upload APK artifact uses: actions/upload-artifact@v2 
        with: 
          name: apk
          path: path/to/C:\Users\Ann Margaret Ruelan\Documents\python\onion bulb diseases detector app\bin\main-debug.apk
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: Upload Python artifacts to GitHub Release uses: actions/upload-release-asset@v1 with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: python-artifacts.zip
          asset_name: python-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: python-artifacts.zip
          asset_name: python-artifacts.zip
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
