name: Build and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Test
        run: |
          # ... build and test code ...

          # Save build artifact
          echo "Build artifact saved as myapp.zip"
          zip -r myapp.zip myapp/
          mv myapp.zip artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: artifacts/myapp.zip
