name: Disease Alert

on:
  push:
    branches: main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: 20

      # ... rest of the workflow ...

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12' # Choose the appropriate version

      - name: Upload Package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python-artifacts
          path: path/to/C:/Users/Ann Margaret Ruelan/Documents/python/onion bulb diseases detector app/main.py.py
          
      - name: Make package available for download
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
              main.py
              utils.py
              requirements.txt
          
